ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Models/Department.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Department_ID { get; set; }
        public int Retailer_ID { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public string image_url { get; set; }
    
        public virtual Retailer Retailer { get; set; }
    }
}

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RetailersApp.Repository;
using RetailersApp.DTO;
using AutoMapper;

namespace RetailersApp.Controllers
{
    public class DepartmentsController : Controller
    {
        private IDepartment department;
        private IRetailer retailer;
        private MapperConfiguration config;
        private IMapper iMapper;

        public DepartmentsController()
        {
            this.department = new Department(new Models.RetailDBEntities());
            this.retailer = new Retailer(new Models.RetailDBEntities());

            config = new MapperConfiguration(cfg => {
                cfg.CreateMap<Models.Retailer, RetailerDto>();
                // AutoMapper congig with nested type
                cfg.CreateMap<Models.Department, DepartmentDto>()
                .ForMember(dest => dest.Retailer, act => act.MapFrom(src => src.Retailer));
            });
            iMapper = config.CreateMapper();
        }

        // GET: Departments
        public ActionResult Index()
        {
            var list = department.GetDepartments().ToList();
            return View(list);
        }

        // GET: Departments/Details/5
        public ActionResult Details(int id)
        {
            var _department = department.GetDepartmentByID(id);
            return View(_department);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var retailers = this.retailer.GetRetailers().ToList();
            ViewBag.Retailer_ID = new SelectList(retailers, "Retailer_ID", "Retailer_Name");
            return View();
        }


        [HttpPost]
        public ActionResult Create(FormCollection collection, Models.Department department)
        {
            try
            {
                Models.Department _department = new Models.Department();
                _department.Retailer_ID = department.Retailer_ID;
                _department.Department_Name = department.Department_Name;
                _department.Department_Code = department.Department_Code;
                _department.Retailer = department.Retailer;

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files["ImageFile"];
                    try
                    {
                        if (file.ContentLength > 0)
                        {
                            string _fileName = Path.GetFileName(file.FileName);
                            string _path = Path.Combine(Server.MapPath("~/Images"), _fileName);
                            _department.image_url = _fileName;
                            file.SaveAs(_path);
                        }
                    }
                    catch
                    {
                        ViewBag.Message = "File upload failed!!";
                        return View();
                    }
                }

                this.department.InsertDepartment(_department);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            /*
            var _department = this.department.GetDepartmentByID(id); // getting records by id GetEmployeeByID(ID)

            var retailers = this.retailer.GetRetailers().ToList();
            ViewBag.Retailer_ID = new SelectList(retailers, "Retailer_ID", "Retailer_Name", _department.Retailer_ID);

            var DepartmentEdit = new Models.Department();
            DepartmentEdit.Department_ID = id;
            DepartmentEdit.Retailer_ID = _department.Retailer_ID;
            DepartmentEdit.Department_Name = _department.Department_Name;
            DepartmentEdit.Department_Code = _department.Department_Code;            
            DepartmentEdit.image_url = _department.image_url;
            return View(DepartmentEdit);
            */

            // Using the Department DTO from the Department Repository
            DTO.DepartmentDto department = this.department.GetDepartmentByID(id);

            // Retailers dropdown
            var retailers = this.retailer.GetRetailers().ToList();
            ViewBag.Retailer_ID = new SelectList(retailers, "Retailer_ID", "Retailer_Name", department.Retailer_ID);

            return View(department);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection, Models.Department department)
        {
            try
            {
                /*
                // Before AutoMapper
                Models.Department _department = new Models.Department();
                _department.Department_ID = department.Department_ID;
                _department.Retailer_ID = department.Retailer_ID;
                _department.Department_Name = department.Department_Name;
                _department.Department_Code = department.Department_Code.Trim();                
                _department.image_url = department.image_url;   // if not new file uploaded
                */

                DepartmentDto _department = iMapper.Map<Models.Department, DepartmentDto>(department);
                

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files["ImageFile"];
                    try
                    {
                        if (file.ContentLength > 0)
                        {
                            // delete old image
                            string oldFilePath = Server.MapPath("~/Images/" + department.image_url);
                            if (System.IO.File.Exists(oldFilePath))
                            {
                                System.IO.File.Delete(oldFilePath);
                            }

                            string _fileName = Path.GetFileName(file.FileName);
                            string _path = Path.Combine(Server.MapPath("~/Images"), _fileName);
                            _department.image_url = _fileName;
                            file.SaveAs(_path);
                        }
                    }
                    catch
                    {
                        ViewBag.Message = "File upload failed!!";
                        return View();
                    }
                }
                this.department.UpdateDepartment(_department.Department_ID, _department);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int id)
        {
            // Before AutoMapper
            //Models.Department department = this.department.GetDepartmentByID(id);

            DTO.DepartmentDto department = this.department.GetDepartmentByID(id); 
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // delete image
                var _department = this.department.GetDepartmentByID(id);
                string filePath = Server.MapPath("~/Images/" + _department.image_url);
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                this.department.DeleteDepartment(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Departments/Create.cshtml
@model RetailersApp.Models.Department

@{
    ViewBag.Title = "Create Retailer";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Departments", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Department</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        <label class="control-label col-md-2">Department Name</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Department_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Department_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">
            Department Code</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department_Code, "", new { @class = "text-danger" })
            </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Retailer Name</label>
        <div class="col-md-10">
            @{
                //Html.EditorFor(model => model.Retailer_ID, new { htmlAttributes = new { @class = "form-control" } })
            }

            @Html.DropDownList("Retailer_ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Retailer_ID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <label class="control-label col-md-2">Image</label>
        <div class="col-md-10">
            <img src="~/Images/image-not-available.jpg" width="150" height="150" id="imG" /><br/><br/>
            <input type="file" name="ImageFile" id="imgUploader" onchange="readURL(this);" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imG')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Departments/Delete.cshtml
@model RetailersApp.DTO.DepartmentDto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <b>Department Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department_Name)
        </dd>

        <dt>
            <b>Department Code</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department_Code)
        </dd>

        <dt>
            <b>Retailer Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Retailer.Retailer_Name)
        </dd>





        <dt>
            <b>Image</b>
        </dt>

        <dd>
            @{
                string img = "";
                if (Model.image_url != null)
                { img = Model.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="~/Images/@img" height="150" width="150" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Departments/Details.cshtml
@model RetailersApp.DTO.DepartmentDto

@{
    ViewBag.Title = "Department Details";
}

<h2>Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Department_Name)</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <b>Department Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department_Name)
        </dd>

        <dt>
            <b>Department Code</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department_Code)
        </dd>

        <dt>
            <b>Retailer Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Retailer.Retailer_Name)
        </dd>

        <dt>
            <b>Image</b>
        </dt>

        <dd>
            @{
                string img = "";
                if (Model.image_url != null)
                { img = Model.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="~/Images/@img" height="150" width="150" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Department_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Departments/Edit.cshtml
@model RetailersApp.DTO.DepartmentDto

@{
    ViewBag.Title = "Edit Department";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Departments", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Department</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("Department_ID", Model.Department_ID)
    @{
        string imgUrl = "";
        if (Model.image_url != null)
        { imgUrl = Model.image_url.ToString().Trim(); }
        else
        { imgUrl = "image-not-available.jpg"; }
    }
    @Html.Hidden("image_url", imgUrl)

    <div class="form-group">
        <label class="control-label col-md-2">Department Name</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Department_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Department_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">
            Department Code
        </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Department_Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Department_Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Retailer Name</label>
        <div class="col-md-10">
            @Html.DropDownList("Retailer_ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Retailer_ID, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <label class="control-label col-md-2">Image</label>
        <div class="col-md-10">
            @{
                string img = "";
                if (Model.image_url != null)
                { img = Model.image_url.ToString().Trim(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img id="imG" src="~/Images/@img" height="150" width="150" /><br /><br />
            <input type="file" name="ImageFile" id="imgUploader" onchange="readURL(this);" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imG')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Departments/Index.cshtml
@model IEnumerable<RetailersApp.Models.Department>

@{
    ViewBag.Title = "Departments";
}

<h2>Departments</h2>

<p>
    @Html.ActionLink("Create New Department", "Create") | @Html.ActionLink("Retailers", "../Retailers/Index") | @Html.ActionLink("Master Details GridView (LINQ)", "../Retailers/Report")
</p>
<table class="table">
    <tr>
        <th>
            Department Name
        </th>
        <th>
            Department Code
        </th>
        <th>
            Retailer Name
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Department_Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Department_Code)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Retailer.Retailer_Name)
        </td>
        <td>
            @{
                //Html.DisplayFor(modelItem => item.image_url)
            }

            @{
                string img = "";
                if (item.image_url != null)
                { img = item.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="~/Images/@img" height="50" width="50" />

        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.Department_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Department_ID }) |
            @Html.ActionLink("Delete", "Delete", new {  id=item.Department_ID })
        </td>
    </tr>
    }

</table>