Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/config/routes.rb
RootNextProject::Application.routes.draw do
  get "root_next/home"

  resources :clients
  root 'root_next#home'

  

end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/models/client.rb
class Client < ActiveRecord::Base
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
http_basic_authenticate_with name: "rootnext", password: "secret"
def index
 @clients = Client.all
end

def new
end

def create
 @client = Client.new(client_params)
 @client.save
 redirect_to @client
end

def show
  @client = Client.find(params[:id])
end

def edit
 @client = Client.find(params[:id])
end

def update
  @client = Client.find(params[:id])
 
  if @client.update(client_params)
    redirect_to @client
  else
    render 'edit'
  end
end

def destroy
  @client = Client.find(params[:id])
  @client.destroy
 
  redirect_to clients_path
end

private
 def client_params
  params.require(:client).permit(:name, :contact_name, :contact_phone, :contact_email, :facebook_email, :facebook_account);
 end
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/controllers/root_next_controller.rb
class RootNextController < ApplicationController
  def home
  end
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/helpers/application_helper.rb
module ApplicationHelper
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/helpers/clients_helper.rb
module ClientsHelper
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/helpers/root_next_helper.rb
module RootNextHelper
end

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/clients/edit.html.erb
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      // document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
		// document.getElementById('client_facebook_email').value = '';
		// document.getElementById('client_facebook_account').value = '';
		
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      // document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
		// document.getElementById('client_facebook_email').value = '';
		// document.getElementById('client_facebook_account').value = '';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1516464231942637',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.1' // use version 2.1
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('client_facebook_email').value =
        response.email;
	document.getElementById('client_facebook_account').value = response.id;	
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<%= field_set_tag 'Edit Client' do %>
<%= form_for :client, url: client_path(@client), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :size=>'40' %>
  </p>
 
  <p>
    <%= f.label :'Contact Name' %><br>
    <%= f.text_field :contact_name, :size=>'40' %>
  </p>
 
 <p>
    <%= f.label :'Contact Phone' %><br>
    <%= f.text_field :contact_phone, :size=>'40' %>
 </p>
 
 <p>
    <%= f.label :'Contact Email' %><br>
    <%= f.text_field :contact_email, :size=>'40' %>
 </p>
 
 
 <p>
    <%= f.label :'Facebook Email' %><br>
    <%= f.text_field :facebook_email, :size=>'40' %>
  </p>
  
  <p>
    <%= f.label :'Facebook Account' %><br>
    <%= f.text_field :facebook_account, :size=>'40' %>
	<fb:login-button scope="public_profile,email" onlogin="checkLoginState();" data-size="large" data-show-faces="faces" data-auto-logout-link="true" >
	</fb:login-button>
  </p>
 
  <p>
    <%= f.submit 'Save' %>
	<%= f.submit 'Cancel', :type=>'reset' %>
  </p>
<% end %>
<%= link_to 'Back to the List', clients_path %>
|
<%= link_to 'View Client', client_path(@client) %>
<% end %>

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/clients/index.html.erb
<div align="center">
<table width="90%">
 <caption>
  <div align="left">
   <%= link_to 'Create New Client', new_client_path %>
  </div>
  <h2>All Clients</h2>
 </caption>
 
  <tr>
    <th>Name</th>
    <th>Contact Name</th>
	<th>Contact Email</th>
    <th>Contact Phone</th>
	<th>Facebook Email</th>
    <th>Facebook Account</th>
	<th></th>
  </tr>
 
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.name %></td>
      <td><%= client.contact_name %></td>
	  <td><a href="mailto:<%= client.contact_email %>"><%= client.contact_email %></a></td>
      <td><%= client.contact_phone %></td>
	  <td><%= client.facebook_email %></td>
      <td><%= client.facebook_account %></td>
	  <td>
	   <%= link_to 'View', client_path(client) %>
	   |
	   <%= link_to 'Edit', edit_client_path(client) %>
	   |
	   <%= link_to 'Delete', client_path(client),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
	  </td>
    </tr>
  <% end %>
</table>
</div>

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/clients/new.html.erb
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      // document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
		document.getElementById('client_facebook_email').value = '';
		document.getElementById('client_facebook_account').value = '';
		
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      // document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
		document.getElementById('client_facebook_email').value = '';
		document.getElementById('client_facebook_account').value = '';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1516464231942637',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.1' // use version 2.1
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('client_facebook_email').value =
        response.email;
	document.getElementById('client_facebook_account').value = response.id;	
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<%= field_set_tag 'Create New Client' do %>
<%= form_for :client, url: clients_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :size=>'40' %>
  </p>
 
  <p>
    <%= f.label :'Contact Name' %><br>
    <%= f.text_field :contact_name, :size=>'40' %>
  </p>
 
 <p>
    <%= f.label :'Contact Phone' %><br>
    <%= f.text_field :contact_phone, :size=>'40' %>
 </p>
 
 <p>
    <%= f.label :'Contact Email' %><br>
    <%= f.text_field :contact_email, :size=>'40' %>
 </p>
 
 
 <p>
    <%= f.label :'Facebook Email' %><br>
    <%= f.text_field :facebook_email , :size=>'40' %>
  </p>
  
  <p>
    <%= f.label :'Facebook Account' %><br>
    <%= f.text_field :facebook_account, :size=>'40' %>
	<fb:login-button scope="public_profile,email" onlogin="checkLoginState();" data-size="large" data-show-faces="faces" data-auto-logout-link="true" >
	</fb:login-button>
  </p>
 
  <p>
    <%= f.submit 'Save' %>
	<%= f.submit 'Cancel', :type=>'reset' %>
  </p>
<% end %>
<%= link_to 'Back to the List', clients_path %>
<% end %>

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/clients/show.html.erb
<%= field_set_tag 'Client Information' do %>
<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>
 
<p>
  <strong>Contact Name:</strong>
  <%= @client.contact_name %>
</p>

<p>
  <strong>Contact Phone:</strong>
  <%= @client.contact_phone %>
</p>
 
<p>
  <strong>Contact Email:</strong>
  <%= @client.contact_email %>
</p>

<p>
  <strong>Facebook Email:</strong>
  <%= @client.facebook_email %>
</p>
 
<p>
  <strong>Facebook Account:</strong>
  <%= @client.facebook_account %>
</p>
<%= link_to 'Back to the List', clients_path %>
|
<%= link_to 'Edit Client', edit_client_path(@client) %>
<% end %>

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RootNextProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

<%= yield %>

</body>
</html>

Rubi on Rails - Sample CRUD app with Facebook - JS authentication/RootNextProject/app/views/root_next/home.html.erb
<h1>RootNext Solutions Limited</h1>
<hr>
<%= link_to 'Test Rails App 1.0', controller: 'clients' %>