ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Models/Retailer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Retailer()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int Retailer_ID { get; set; }
        public string Retailer_Code { get; set; }
        public string Retailer_Name { get; set; }
        public string Retailer_Location { get; set; }
        public string image_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/ViewModels/RetailerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RetailersApp.ViewModels
{
    public class RetailerViewModel
    {
        public int RetailerID { get; set; }
        public string RetailerCode { get; set; }
        public string RetailerName { get; set; }
        public string RetailerLocation { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
    }
}

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Controllers/RetailersController.cs
using System;
using System.Collections.Generic;

using System.IO;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;

using System.Linq;
using System.Web;
using System.Web.Mvc;
using RetailersApp.Repository;
using RetailersApp.GoogleDriveAPI;

namespace RetailersApp.Controllers
{
    public class RetailersController : Controller
    {
        private IRetailer retailer;
        private IDepartment department;

        public RetailersController()
        {
            this.retailer = new Retailer(new Models.RetailDBEntities());
            this.department = new Department(new Models.RetailDBEntities());
        }

        // GET: Retailers
        public ActionResult Index()
        {
            var list = retailer.GetRetailers().ToList();
            return View(list);
        }

        // GET: Retailers/Details/5
        public ActionResult Details(int id)
        {
            var _retailer = retailer.GetRetailerByID(id);
            return View(_retailer);
        }

        [HttpGet]
        public ActionResult Create()

        {
            return View(new Models.Retailer());

        }

        [HttpPost]
        public ActionResult Create(FormCollection collection, Models.Retailer retailer)
        {
            try
            {
                Models.Retailer _retailer = new Models.Retailer();
                _retailer.Retailer_Name = retailer.Retailer_Name;
                _retailer.Retailer_Code = retailer.Retailer_Code;
                _retailer.Retailer_Location = retailer.Retailer_Location;

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files["ImageFile"];
                    try
                    {
                        if (file.ContentLength > 0)
                        {
                            string _fileName = Path.GetFileName(file.FileName);
                            string _path = Path.Combine(Server.MapPath("~/Images"), _fileName);
                            _retailer.image_url = _fileName;
                            file.SaveAs(_path);
                        }
                    }
                    catch
                    {
                        ViewBag.Message = "File upload failed!!";
                        return View();
                    }
                }
                
                this.retailer.InsertRetailer(_retailer);                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var _retailer = this.retailer.GetRetailerByID(id); // getting records by id GetEmployeeByID(ID)

            var retailerEdit = new Models.Retailer();
            retailerEdit.Retailer_ID = id;
            retailerEdit.Retailer_Name = _retailer.Retailer_Name;
            retailerEdit.Retailer_Code = _retailer.Retailer_Code;
            retailerEdit.Retailer_Location = _retailer.Retailer_Location;
            retailerEdit.image_url = _retailer.image_url;
            return View(retailerEdit);
        }

        [HttpPost]
        public ActionResult Edit(FormCollection collection, Models.Retailer retailer)
        {
            try
            {

             Models.Retailer _retailer = new Models.Retailer();
            _retailer.Retailer_ID = retailer.Retailer_ID;
            _retailer.Retailer_Name = retailer.Retailer_Name;
            _retailer.Retailer_Code = retailer.Retailer_Code.Trim();
            _retailer.Retailer_Location = retailer.Retailer_Location;
            _retailer.image_url = retailer.image_url;   // if not new file uploaded

                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase file = Request.Files["ImageFile"];
                    try
                    {
                        if (file.ContentLength > 0)
                        {
                        // delete old image
                        string oldFilePath = Server.MapPath("~/Images/" + retailer.image_url);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }

                        string _fileName = Path.GetFileName(file.FileName);
                            string _path = Path.Combine(Server.MapPath("~/Images"), _fileName);
                            _retailer.image_url = _fileName;
                            file.SaveAs(_path);
                        }
                    }
                    catch
                    {
                        ViewBag.Message = "File upload failed!!";
                        return View();
                    }
                }

                this.retailer.UpdateRetailer(_retailer);

                return RedirectToAction("Index");

            }

            catch

            {

                return View();

            }

        }

        // GET: Retailers/Delete/5
        public ActionResult Delete(int id)
        {
            Models.Retailer retailer = this.retailer.GetRetailerByID(id);
            return View(retailer);
        }

        // POST: Retailers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // delete image
                var _retailer = retailer.GetRetailerByID(id);
                string filePath = Server.MapPath("~/Images/" + _retailer.image_url);
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                this.retailer.DeleteRetailer(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // Combined Report (LINQ)
        public ActionResult Report()
        {
            //var _retailers = this.retailer.GetRetailers().ToList();
            List<Models.Retailer> retailers = this.retailer.GetRetailers().ToList();

            //var _departments = this.department.GetDepartments().ToList();
            List<Models.Department> departments = this.department.GetDepartments().ToList();

            
            var query = (from r in retailers
                        join d in departments on r.Retailer_ID equals d.Retailer_ID 
                        select new ViewModels.RetailerViewModel { RetailerID = r.Retailer_ID, RetailerName = r.Retailer_Name, RetailerCode = r.Retailer_Code, RetailerLocation = r.Retailer_Location, DepartmentName = d.Department_Name, DepartmentCode = d.Department_Code }).ToList();

            return View(query);
        }

        [HttpPost]
        [ValidateInput(false)]
        public FileResult ExportPdf(string content)
        {
           
                    using (MemoryStream stream = new System.IO.MemoryStream())
                    {
                        StringReader sr = new StringReader(content);
                        Document pdfDoc = new Document(PageSize.A4, 30f, 20f, 30f, 20f);
                        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                        pdfDoc.Open();
                        XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                        pdfDoc.Close();
                        return File(stream.ToArray(), "application/pdf", "Report.pdf");
                    }
                 
        }

        [HttpPost]
        [ValidateInput(false)]
        public FileResult ExportExcel(string content)
        {
            return File(Encoding.ASCII.GetBytes(content), "application/vnd.ms-excel", "Report.xls");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ExportGdrive(string content)
        {
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(content);
                Document pdfDoc = new Document(PageSize.A4, 30f, 20f, 30f, 20f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, new FileStream(Server.MapPath("~/GDrive/Report.pdf"), FileMode.Create)); //PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                
                pdfDoc.Close();

                FileStream file = System.IO.File.Open(Server.MapPath("~/GDrive/Report.pdf"), FileMode.Open); //System.IO.File.Open( ("~/GDrive/Report.pdf");
                
                // Upload file to root folder
                //GoogleDriveAPIHelper.UplaodFileOnDrive(file);

                // Upload file to specific folder
                GoogleDriveAPIHelper.FileUploadInFolder("1bEuGDeH8jKmBsOvwJl0AVKfalF0OHlPR", file);
                ViewBag.Success = "File Uploaded on Google Drive.";
                return View();             
            }
        }

    }
}

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Create.cshtml
@model RetailersApp.Models.Retailer

@{
    ViewBag.Title = "Create Retailer";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Retailers", FormMethod.Post, new
            {
                enctype = "multipart/form-data"
            })) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Retailer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            <label class = "control-label col-md-2">Retailer Code</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Retailer_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Retailer_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Retailer Name</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Retailer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Retailer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Location</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Retailer_Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Retailer_Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Image</label>
            <div class="col-md-10">
                <img src="~/Images/image-not-available.jpg" width="150" height="150" id="imG" /><br/><br/>
                <input type="file" name="ImageFile" id="imgUploader" onchange="readURL(this);" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imG')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Delete.cshtml
@model RetailersApp.Models.Retailer

@{
    ViewBag.Title = "Delete Retailer";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Retailer</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <b>Retailer Code</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Retailer_Code)
        </dd>

        <dt>
            <b>Retailer Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Retailer_Name)
        </dd>

        <dt>
            <b>Location</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Retailer_Location)
        </dd>

        <dt>
            <b>Image</b>
        </dt>

        <dd>
            @{ 
                //Html.DisplayFor(model => model.image_url) 
            }
            
            @{
                string img = "";
                if (Model.image_url != null)
                { img = Model.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="~/Images/@img" height="150" width="150" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Details.cshtml
@model RetailersApp.Models.Retailer

@{
    ViewBag.Title = "Retailer Details";
}

<h2>Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Retailer_Name)</h4>
    <hr />
    
        <dl class="dl-horizontal">           

            <dt>
                <b>Retailer Code</b>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Retailer_Code)
            </dd>

            <dt>
                <b>Retailer Name</b>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Retailer_Name)
            </dd>

            <dt>
                <b>Location</b>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Retailer_Location)
            </dd>

            <dt>
                <b>Image</b>
            </dt>

            <dd>
                
                @{
                    string img = "";
                    if (Model.image_url != null)
                    { img = Model.image_url.ToString(); }
                    else
                    { img = "image-not-available.jpg"; }
                }
                <img src="~/Images/@img" height="150" width="150" />
            </dd>

        </dl>
    
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Retailer_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Edit.cshtml
@model RetailersApp.Models.Retailer

@{
    ViewBag.Title = "Edit Retailer";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Retailers", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Retailer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("Retailer_ID", Model.Retailer_ID)
    @Html.Hidden("image_url", Model.image_url)

    <div class="form-group">
        <label class="control-label col-md-2">Retailer Code</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Retailer_Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Retailer_Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Retailer Name</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Retailer_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Retailer_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Location</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Retailer_Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Retailer_Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Image</label>
        <div class="col-md-10">
            @{
                string img = "";
                if (Model.image_url != null)
                { img = Model.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="~/Images/@img" height="150" width="150" id="imG" /><br/><br/>
            <input type="file" name="ImageFile" id="imgUploader" onchange="readURL(this);" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imG')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(150);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/ExportGdrive.cshtml
@{
    ViewBag.Title = "Export to Google Drive";
}

<h2>File being copied to Google drive...</h2>

<hr/><p>@ViewBag.Success</p>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Index.cshtml
@model IEnumerable<RetailersApp.Models.Retailer>

@{
    ViewBag.Title = "Retailers";
}

<h2>Retailers</h2>

<p>
    @Html.ActionLink("Create New Retailer", "Create") | @Html.ActionLink("Departments", "../Departments/Index") | @Html.ActionLink("Master Details GridView (LINQ)", "Report")
</p>
<table class="table">
    <tr>
        
        <th>
            Retailer Code
        </th>
        <th>
            Retailer Name
        </th>
        <th>
            Location
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>        
        <td>
            @Html.DisplayFor(modelItem => item.Retailer_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Retailer_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Retailer_Location)
        </td>
        <td>

            @{
                string img = "";
                if (item.image_url != null)
                { img = item.image_url.ToString(); }
                else
                { img = "image-not-available.jpg"; }
            }
            <img src="../Images/@img" height="50" width="50" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Retailer_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Retailer_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Retailer_ID })
        </td>
    </tr>
}

</table>

ASP.NET MVC - application-with-Repository-Pattern-PDF-creation-and-Google-Drive-API/RetailersApp/RetailersApp/Views/Retailers/Report.cshtml
@model IEnumerable<RetailersApp.ViewModels.RetailerViewModel>

@{
    ViewBag.Title = "Master Details GridView (LINQ)";
}

<h2>Master Details GridView (LINQ)</h2>

<p>
    @Html.ActionLink("Retailers", "Index") | @Html.ActionLink("Departments", "../Departments/Index")
</p>

<table class="table">
    <tr>
        <!--th>
        @{
            //Html.DisplayNameFor(model => model.RetailerID)
        }
        </th-->

        <th><input type="checkbox" id="chkAll" /></th>

        <th>
            Retailer Name
        </th>
        <th>
            Retailer Code
        </th>

        <th>
            Retailer Location
        </th>
        <th>
            Department Name
        </th>
        <th>
            Department Code
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><input type="checkbox" /></td>

            <td>
                @Html.DisplayFor(modelItem => item.RetailerName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.RetailerCode)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.RetailerLocation)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DepartmentCode)
            </td>

        </tr>
    }

</table>

<div class="col-sm-2">
    <button class="btn btn-primary form-control" id="btnPdf">Export to PDF</button>
</div>
<div class="col-sm-2">
    <button class="btn btn-primary form-control" id="btnExcel">Export to Excel</button>
</div>
<!--
<div class="col-sm-3">
    <button class="btn btn-primary form-control" id="btnGSheet">Export to Google Spreadsheet</button>
</div>
-->

<div class="col-sm-3">
    <button class="btn btn-primary form-control" id="btnGdrive">Export PDF to Google Drive</button>
</div>
<p>&nbsp;</p>

@using (Html.BeginForm("ExportPdf", "Retailers", FormMethod.Post))
{
    @Html.Hidden("content")
}

<script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>

<script>

    $("#chkAll").click(function () {
        if (this.checked) {
            $('input:checkbox').not(this).prop('checked', this.checked); //$('#keepSelected').removeClass('btn disabled');
        }
        else {
            $('input:checkbox').not(this).prop('checked', ''); //$('#keepSelected').addClass('btn disabled');
        }
    });

    $('input:checkbox').not($('#chkAll')).click(function () {
        $('#chkAll').prop('checked', '');
    });

    $('#btnPdf').click(function () {
        var pdfcontent = getContent();
        $('#content').val(pdfcontent);
        document.forms[0].action = "../Retailers/ExportPdf";
        document.forms[0].submit();
    });

    $('#btnExcel').click(function () {
        var content = getContent();
        $('#content').val(content);
        document.forms[0].action = "../Retailers/ExportExcel";
        document.forms[0].submit();
    });

    $('#btnGdrive').click(function () {
        var content = getContent();
        $('#content').val(content);
        document.forms[0].action = "http://localhost:5000/Retailers/ExportGdrive";
        document.forms[0].submit();
    });

    function getContent() {
        var content = ""; ///"<style>th{border-bottom: 1px solid #ff0000;}</style>";
        content += "<h1>Master Details GridView (LINQ)</h1>";
        content += "<table border=\"0\" cellpadding=\"5\" cellspacing=\"0\" width=\"95%\">";

        content += "<tr>";
        content += "<th style=\"border-bottom: 1px solid #ff0000;\">Retailer Name</th>";
        content += "<th style=\"border-bottom: 1px solid #ff0000;\">";
        content += "Retailer Code";
        content += "</th>";
        content += "<th style=\"border-bottom: 1px solid #ff0000;\">";
        content += "Retailer Location";
        content += "</th>";
        content += "<th style=\"border-bottom: 1px solid #ff0000;\">";
        content += "Department Name";
        content += "</th>";
        content += "<th style=\"border-bottom: 1px solid #ff0000;\">";
        content += "Department Code";
        content += "</th>";
        content += "</tr>";

        $('input:checkbox:checked').not($('#chkAll')).parents("tr").each(function () {
            var td = $(this).find("td:first");
            $(this).find("td:first").remove();
            content += "<tr>";
            content += $(this).html();
            content += "</tr>";
            $(this).prepend("<td>" + td.html() + "</td>");
        });

        content += "</table>";
        console.log(content);
        $('#chkAll').prop('checked', '');
        return content;
    }

</script>